version: '3'

services:
    nodejs:
        container_name: nodejs-user-admin
        image: node:8
        volumes:
            - .:/project
        ports:
            - "8080:8080"
        command: ["bash","-c", "npm install && npm start"]
        working_dir: /project

    backend:
        build: UserAdminBackend
        container_name: apache-user-admin
        image: enbock/user-admin-backend
        volumes:
            - .:/var/www
        ports:
             - "8090:80"

networks:
    default:
        external:
            name: user-admin
